spring:
  application:
    name: zuul-gateway    
server:
  port: 8762
#  context-path: /client


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  routes:
#     gallary:
#       path: /res/gallary/**
#       serviceId: gallery-service
#     image:
#       path: /res/images/**
#       serviceId: image-service
spring.cloud.gateway:
  routes:
  - id: test
    uri: lb://image-service
    predicates:
    - Path=/res/images/**

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
       
#OKTA
#security:
#  oauth2:
#    client:
#      clientId: 0oahavcv5dX2PQxni0h7
#      clientSecret: gP3mB5GqNNrGXuJgv82NthE8sxAGZBl_zLWkdKE6
#      access-token-uri: https://dev-478432.oktapreview.com/oauth2/default/v1/token
#      user-authorization-uri: https://dev-478432.oktapreview.com/oauth2/default/v1/authorize    
#    resource:    
#      user-info-uri: https://dev-478432.oktapreview.com/oauth2/default/v1/userinfo
#      prefer-token-info: false

#Azure B2C
security:
  basic:
    enabled: false
#    ignored: /welcome,/favicon.ico,/index.html,/signup,/assets/**,/js/**,/css/**,/webjars/**
#    sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /login
    client:
#    "issuer": "https://umediax.b2clogin.com/c50b6a84-4651-40db-935a-837ed5a67a95/v2.0/",  ???    
      clientId: 111ddde5-38af-4c31-a540-f204d64ccc5e
      clientSecret: /8D^F792t2r/%3T`89XXGPXE
#      ?p=b2c_1_signinup",
      access-token-uri: https://login.microsoftonline.com/te/umediax.onmicrosoft.com/b2c_1_signinup/oauth2/v2.0/token
#       https://umediax.b2clogin.com/umediax.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_signinup
      user-authorization-uri: https://login.microsoftonline.com/te/umediax.onmicrosoft.com/b2c_1_signinup/oauth2/v2.0/authorize
      scope: https://umediax.onmicrosoft.com/signinup/user_impersonation+openid+offline_access
#      scope: openid
#      authorizedGrantTypes: client_credentials
#      grant-type: USER
      auto-approve-scopes: true
      authorizedGrantTypes: authorization_code
#      auto-approve-scopes: '.*'
      clientAuthenticationScheme: form   
    resource:   
      issuer: https://umediax.b2clogin.com/c50b6a84-4651-40db-935a-837ed5a67a95/v2.0/ 
#      user-info-uri: https://login.microsoftonline.com/te/umediax.onmicrosoft.com/b2c_1_signinup/oauth2/v2.0/userinfo
      jwk:
        key-set-uri: https://login.microsoftonline.com/te/umediax.onmicrosoft.com/b2c_1_signinup/discovery/v2.0/keys
      prefer-token-info: true
#      jwt:
#       #keyValue or key-value?
#       key-value: tVKUtcx_n9rt5afY_2WFNvU6PlFMggCatsZ3l4RjKxH0jgdLq6CScb0P3ZGXYbPzXvmmLiWZizpb-h0qup5jznOvOr-Dhw9908584BSgC83YacjWNqEK3urxhyE2jWjwRm2N95WGgb5mzE5XmZIvkvyXnn7X8dvgFPF5QwIngGsDG8LyHuJWlaDhr_EPLMW4wHvH0zZCuRMARIJmmqiMy3VD4ftq4nS5s8vJL0pVSrkuNojtokp84AtkADCDU_BUhrc2sIgfnvZ03koCQRoZmWiHu86SuJZYkDFstVTVSR0hiXudFlfQ2rOhPlpObmku68lXw-7V-P7jwrQRFfQVXw
#       key-set-uri: https://login.microsoftonline.com/te/umediax.onmicrosoft.com/b2c_1_signinup/discovery/v2.0/keys
     
